/* =========================================================
   ISO 9001:2026 GAP ASSESSMENT — Question bank (manufacturing)
   Questions are paraphrased for auditing; they are not the
   text of the standard. `change` marks requirements that are
   new or technically modified compared with ISO 9001:2015
   (editorial and renumbering changes are not flagged).
   ========================================================= */

const ISO_CLAUSES = [
  {
    num: '4', title: 'Context of the organization',
    items: [
      { id: '4.1-a', ref: '4.1', title: 'Understanding the organization and its context',
        q: 'How has the organization identified the external and internal issues that affect the plant\'s ability to achieve the intended results of the QMS (e.g. raw material supply, market demand, technology, regulation, workforce skills, capacity)?',
        ev: 'Context / SWOT / PESTLE register, strategy or business plan, management review minutes' },
      { id: '4.1-b', ref: '4.1', title: 'Climate change as a relevant issue',
        q: 'Has the organization determined whether climate change is a relevant issue (e.g. energy cost and availability, extreme weather affecting the plant or supply chain, customer carbon or sustainability requirements) and recorded the conclusion?',
        ev: 'Context register entry on climate change with conclusion and rationale',
        change: { type: 'New', text: 'The organization must explicitly decide whether climate change is a relevant issue. This was not in ISO 9001:2015 (it was introduced by Amendment 1:2024 and is now part of the standard).' } },
      { id: '4.1-c', ref: '4.1', title: 'Monitoring of issues',
        q: 'How, how often and by whom is information about these internal and external issues monitored and reviewed?',
        ev: 'Review dates on context register, MR inputs' },
      { id: '4.2-a', ref: '4.2', title: 'Relevant interested parties and their requirements',
        q: 'Have relevant interested parties been identified (customers/OEMs, regulators, suppliers, employees, contractors, local community, certification body) together with their relevant requirements, including any climate-related expectations?',
        ev: 'Interested party register with needs/expectations' },
      { id: '4.2-b', ref: '4.2 c)', title: 'Requirements addressed through the QMS',
        q: 'Has the organization decided which of the interested parties\' requirements will be addressed through the QMS (and which will not)?',
        ev: 'Interested party register column "addressed through QMS: Yes/No" with link to the process that handles it',
        change: { type: 'New', text: 'New item c): the organization must determine which interested-party requirements will be addressed through the QMS. ISO 9001:2015 only required identifying parties and their requirements.' } },
      { id: '4.2-c', ref: '4.2', title: 'Monitoring of interested parties',
        q: 'Is information about interested parties and their requirements monitored and reviewed at a defined frequency?',
        ev: 'Register review records, MR minutes' },
      { id: '4.3-a', ref: '4.3', title: 'Scope of the QMS',
        q: 'Is the QMS scope documented, stating the products and services and the sites/activities covered, and does it take account of 4.1 issues, 4.2 requirements and the products made?',
        ev: 'Quality manual / scope statement, certificate scope' },
      { id: '4.3-b', ref: '4.3', title: 'Justification of non-applicable requirements',
        q: 'Where any requirement is declared not applicable (e.g. 8.3 for build-to-print manufacturers), is a justification documented, and does it not affect product conformity or customer satisfaction?',
        ev: 'Scope document with justification' },
      { id: '4.4-a', ref: '4.4.1', title: 'QMS processes and interactions',
        q: 'Have the QMS processes been determined with their inputs, outputs, sequence and interactions (e.g. sales → planning → purchasing → production → inspection → dispatch)?',
        ev: 'Process map, process interaction matrix, turtle diagrams' },
      { id: '4.4-b', ref: '4.4.1', title: 'Process criteria, resources and responsibilities',
        q: 'For each process, are criteria and methods (including monitoring and KPIs), resources, responsibilities and authorities, and related risks and opportunities defined?',
        ev: 'Process owner list, KPI sheet, procedures' },
      { id: '4.4-c', ref: '4.4.1', title: 'Process evaluation and improvement',
        q: 'Are processes evaluated, and are changes made where needed so they achieve their intended results?',
        ev: 'Process performance reviews, KPI trends, improvement records' },
      { id: '4.4-d', ref: '4.4.2', title: 'Documented information for processes',
        q: 'Is documented information available to support process operation (SOPs, work instructions, control plans) and as evidence that processes are carried out as planned (records)?',
        ev: 'Document master list, records list' }
    ]
  },
  {
    num: '5', title: 'Leadership',
    items: [
      { id: '5.1.1-a', ref: '5.1.1', title: 'Leadership and commitment',
        q: 'How does top management show commitment: quality policy and objectives aligned to strategy, QMS integrated into business processes, resources made available, and accountability taken for QMS effectiveness?',
        ev: 'Interview with top management, business plan, budget approvals, MR minutes' },
      { id: '5.1.1-b', ref: '5.1.1', title: 'Engaging and supporting people',
        q: 'How does top management communicate the importance of quality, direct and support people, promote continual improvement and support other managers in their leadership roles?',
        ev: 'Town halls, quality meetings, Gemba walks, improvement schemes' },
      { id: '5.1.1-c', ref: '5.1.1 i)', title: 'Quality culture and ethical behaviour',
        q: 'How does top management promote quality culture and ethical behaviour (e.g. code of conduct, encouraging people to stop the line or raise quality concerns without fear, no pressure to ship nonconforming product, honest reporting of test results)?',
        ev: 'Code of conduct/ethics policy, speak-up or whistle-blower mechanism, quality culture survey, recognition schemes, interviews on the shop floor',
        change: { type: 'New', text: 'New item i): top management must promote quality culture and ethical behaviour. Not present in ISO 9001:2015.' } },
      { id: '5.1.1-d', ref: '5.1.1 j), k)', title: 'Process approach, risk-based and opportunity-based thinking',
        q: 'Does top management promote the process approach together with both risk-based thinking and opportunity-based thinking in decision making?',
        ev: 'MR minutes, strategic planning records, risk and opportunity registers in use',
        change: { type: 'Modified', text: 'ISO 9001:2015 required promoting risk-based thinking; 2026 adds opportunity-based thinking as a distinct concept.' } },
      { id: '5.1.2-a', ref: '5.1.2', title: 'Customer focus',
        q: 'Does top management ensure customer and statutory/regulatory requirements (e.g. product safety, BIS/CE, RoHS/REACH) are determined and met, risks to conformity are addressed, and focus on customer satisfaction is maintained (OTIF, complaints, scorecards)?',
        ev: 'Customer scorecards, complaint trends, legal register for products' },
      { id: '5.2-a', ref: '5.2.1', title: 'Establishing the quality policy',
        q: 'Is the quality policy appropriate to the organization\'s purpose and context, supportive of strategic direction, a framework for objectives, and does it include commitments to meet requirements and to continual improvement?',
        ev: 'Quality policy (signed, dated)' },
      { id: '5.2-b', ref: '5.2.2', title: 'Communicating the quality policy',
        q: 'Is the policy documented, communicated, understood and applied (check with operators), and available to interested parties as appropriate?',
        ev: 'Displayed policy, induction records, website, operator interviews' },
      { id: '5.3-a', ref: '5.3', title: 'Roles, responsibilities and authorities',
        q: 'Are responsibilities and authorities assigned and communicated, including who may release product, stop production or approve concessions?',
        ev: 'Organization chart, job descriptions, authority matrix' },
      { id: '5.3-b', ref: '5.3', title: 'QMS responsibilities',
        q: 'Is responsibility assigned for QMS conformity, reporting on QMS performance and improvement opportunities, promoting customer focus, and maintaining QMS integrity when changes are planned and implemented?',
        ev: 'Appointment letter (QMS coordinator/MR), job descriptions' }
    ]
  },
  {
    num: '6', title: 'Planning',
    items: [
      { id: '6.1.1-a', ref: '6.1.1', title: 'Determining risks and opportunities',
        q: 'When planning the QMS, are the 4.1 issues and 4.2 requirements used to determine risks and opportunities that need to be addressed?',
        ev: 'Link between context/interested-party registers and risk & opportunity registers' },
      { id: '6.1.2-a', ref: '6.1.2', title: 'Analysing and evaluating risks',
        q: 'Are risks that could affect consistent delivery of conforming product and customer satisfaction determined, analysed and evaluated (e.g. risk register with likelihood/severity, PFMEA), including disruption risks such as machine breakdown, single-source suppliers or power failure?',
        ev: 'Risk register with ratings, PFMEA, business continuity / contingency plans',
        change: { type: 'Modified', text: 'Risks are now a separate sub-clause and must be determined, analysed AND evaluated. ISO 9001:2015 only required risks to be determined and addressed together with opportunities.' } },
      { id: '6.1.2-b', ref: '6.1.2', title: 'Actions to address risks',
        q: 'Are actions planned for the risks, integrated into QMS processes, evaluated for effectiveness, and proportionate to the potential impact on the intended results of the QMS?',
        ev: 'Action owners and dates in risk register, effectiveness review records',
        change: { type: 'Modified', text: 'Proportionality is now judged against the impact on the intended results of the QMS (2015: impact on conformity of products and services).' } },
      { id: '6.1.3-a', ref: '6.1.3', title: 'Analysing and evaluating opportunities',
        q: 'Are opportunities (e.g. automation, new products or markets, new materials, digitalization/Industry 4.0, new partnerships) determined, analysed and evaluated separately from risks?',
        ev: 'Opportunity register or separate section, evaluation criteria',
        change: { type: 'New', text: 'New sub-clause: opportunities must be determined, analysed and evaluated in their own right. In ISO 9001:2015 they were combined with risks.' } },
      { id: '6.1.3-b', ref: '6.1.3', title: 'Actions to address opportunities',
        q: 'Are actions planned for selected opportunities, integrated into processes, evaluated for effectiveness, and appropriate to the organization\'s context?',
        ev: 'Opportunity action plans, project charters, effectiveness review',
        change: { type: 'New', text: 'New requirement to plan, integrate and evaluate actions specifically for opportunities, appropriate to the context and supporting desired results.' } },
      { id: '6.2-a', ref: '6.2.1', title: 'Quality objectives',
        q: 'Are quality objectives set at relevant functions, levels and processes (e.g. customer PPM, scrap %, first-pass yield, on-time delivery), and are they measurable, monitored, communicated, updated and documented?',
        ev: 'Objectives sheet with targets, trend charts, display boards' },
      { id: '6.2-b', ref: '6.2.2', title: 'Planning to achieve objectives',
        q: 'For each objective, is it defined what will be done, resources, who is responsible, completion date and how results will be evaluated?',
        ev: 'Objective action plans' },
      { id: '6.3-a', ref: '6.3', title: 'Planned changes to the QMS',
        q: 'When QMS changes occur (e.g. new production line, plant relocation, ERP change, restructuring), are they planned considering purpose and consequences, QMS integrity, resources and information, and allocation of responsibilities?',
        ev: 'Change request / management of change records' },
      { id: '6.3-b', ref: '6.3 e)–g)', title: 'Communicating and evaluating changes',
        q: 'Does the change plan also define how the change will be communicated, how its effectiveness will be monitored and evaluated, and how its results will be reviewed?',
        ev: 'MoC form with communication plan, effectiveness check and post-change review',
        change: { type: 'New', text: 'Strengthened management of change: new items e) communication of changes, f) monitoring and evaluating effectiveness, g) reviewing results, so changes achieve intended results.' } }
    ]
  },
  {
    num: '7', title: 'Support',
    items: [
      { id: '7.1.1-a', ref: '7.1.1', title: 'Resources – general',
        q: 'Have resources needed for the QMS been determined and provided, considering internal capabilities/constraints and what must be obtained from external providers?',
        ev: 'Budget, capacity planning, make-or-buy decisions' },
      { id: '7.1.2-a', ref: '7.1.2', title: 'People',
        q: 'Are sufficient people provided for operating and controlling processes (e.g. manpower planning per shift, back-up for critical roles)?',
        ev: 'Manpower plan, shift rosters' },
      { id: '7.1.3-a', ref: '7.1.3', title: 'Infrastructure',
        q: 'Is the infrastructure (buildings, utilities, machines, tooling, software, transport, IT) determined, provided and maintained (preventive maintenance plan, breakdown records, spares)?',
        ev: 'Machine list, PM schedule and records, breakdown log, IT backup' },
      { id: '7.1.4-a', ref: '7.1.4', title: 'Environment for the operation of processes',
        q: 'Is the necessary work environment determined and maintained: physical factors (temperature, humidity, cleanliness, ESD, lighting, noise) and social/psychological factors?',
        ev: 'Environmental monitoring records, 5S audits, clean-room/ESD controls' },
      { id: '7.1.5-a', ref: '7.1.5.1', title: 'Monitoring and measuring resources',
        q: 'Are measuring instruments and test equipment suitable for the measurements made and maintained fit for purpose, with documented evidence?',
        ev: 'Gauge/instrument master list, MSA/Gauge R&R studies' },
      { id: '7.1.5-b', ref: '7.1.5.2', title: 'Measurement traceability',
        q: 'Are instruments calibrated or verified at intervals against traceable standards (e.g. NABL-accredited labs), identified with calibration status and protected from adjustment or damage?',
        ev: 'Calibration certificates, calibration labels, calibration schedule' },
      { id: '7.1.5-c', ref: '7.1.5.2', title: 'Out-of-calibration action',
        q: 'When equipment is found out of calibration, is the validity of previous measurement results assessed and action taken on affected product?',
        ev: 'Out-of-tolerance investigation records, product recall/re-inspection' },
      { id: '7.1.6-a', ref: '7.1.6', title: 'Organizational knowledge',
        q: 'Is the knowledge needed for processes (process know-how, lessons learnt, failure history, drawings, special-process parameters) determined, and is it retained, applied and shared?',
        ev: 'Lessons learnt database, OPLs (one-point lessons), technical library, succession / knowledge transfer plans',
        change: { type: 'Modified', text: 'Knowledge must now be "retained, applied and shared" (2015: "maintained and made available"). Expect evidence that knowledge is actually used and passed on.' } },
      { id: '7.1.6-b', ref: '7.1.6', title: 'Acquiring new knowledge',
        q: 'When addressing changing needs and trends, does the organization consider current knowledge and determine how to obtain additional knowledge and updates?',
        ev: 'Training on new technology, benchmarking, standards subscriptions' },
      { id: '7.2-a', ref: '7.2', title: 'Competence requirements',
        q: 'Is required competence defined for people affecting quality (operators, inspectors, welders, special-process operators, auditors), and are they competent based on education, training or experience?',
        ev: 'Skill matrix, job descriptions, qualification certificates' },
      { id: '7.2-b', ref: '7.2', title: 'Training and effectiveness',
        q: 'Where gaps exist, are actions taken (training, mentoring, hiring) and their effectiveness evaluated, with records retained?',
        ev: 'Training plan and records, effectiveness evaluation' },
      { id: '7.3-a', ref: '7.3', title: 'Awareness',
        q: 'Are people aware of the quality policy, relevant objectives, their contribution (including benefits of improved performance) and the implications of not conforming?',
        ev: 'Operator interviews, induction records, toolbox talks' },
      { id: '7.3-b', ref: '7.3 e)', title: 'Awareness of quality culture and ethical behaviour',
        q: 'Are people aware of the organization\'s quality culture and expected ethical behaviour (e.g. how to raise concerns, not hiding defects, honest records)?',
        ev: 'Induction content, code of conduct training, interviews',
        change: { type: 'New', text: 'New item e): awareness of the organizational quality culture and ethical behaviour.' } },
      { id: '7.4-a', ref: '7.4', title: 'Communication',
        q: 'Are internal and external communications defined: what, when, with whom, how and who communicates (e.g. shift handover, quality alerts, customer notifications)?',
        ev: 'Communication matrix, meeting minutes, quality alerts' },
      { id: '7.5-a', ref: '7.5.1', title: 'Documented information – general',
        q: 'Does the QMS include the documented information required by the standard and that the organization determined necessary?',
        ev: 'Master list of documents and records' },
      { id: '7.5-b', ref: '7.5.2', title: 'Creating and updating',
        q: 'Do documents have suitable identification (title, number, revision, date), format and media, and are they reviewed and approved before issue?',
        ev: 'Sample SOPs, drawings, approval signatures' },
      { id: '7.5-c', ref: '7.5.3', title: 'Control of documented information',
        q: 'Are current documents available at point of use (latest drawing revision on the shop floor), protected, distributed, stored, version-controlled, retained and disposed of correctly, including documents of external origin (customer drawings, standards)?',
        ev: 'Shop-floor document check, obsolete document control, external document list' },
      { id: '7.5-d', ref: '7.5.3', title: 'Protection of records',
        q: 'Are records kept as evidence of conformity protected from unintended alteration (access rights, backups, controlled templates)?',
        ev: 'ERP/DMS access rights, backup logs' }
    ]
  },
  {
    num: '8', title: 'Operation',
    items: [
      { id: '8.1-a', ref: '8.1', title: 'Operational planning and control',
        q: 'Are production processes planned with product requirements, acceptance criteria, process criteria and resources (e.g. control plans, routings, quality plans), and are they controlled to those criteria?',
        ev: 'Control plan, routing, quality plan, process parameter sheets' },
      { id: '8.1-b', ref: '8.1', title: 'Control of changes and outsourced processes',
        q: 'Are planned changes controlled and the consequences of unintended changes reviewed, and are outsourced processes (e.g. heat treatment, plating, machining) controlled?',
        ev: 'Change records, outsourced process list with controls' },
      { id: '8.2.1-a', ref: '8.2.1', title: 'Customer communication',
        q: 'Is there a defined way to give product information, handle enquiries, orders and changes, obtain feedback including complaints, and handle customer property?',
        ev: 'Catalogues, order handling procedure, complaint register' },
      { id: '8.2.1-b', ref: '8.2.1 e)', title: 'Informing customers about contingencies and disruptions',
        q: 'When relevant, does the organization inform customers about contingency actions, including disruptions to supply (e.g. breakdown, material shortage, force majeure), and how this will be handled?',
        ev: 'Contingency plan with customer notification steps, sample notifications',
        change: { type: 'Modified', text: '2015 required "establishing specific requirements for contingency actions". 2026 requires providing customers with information on contingency actions, including disruptions to provision of products and services.' } },
      { id: '8.2.2-a', ref: '8.2.2', title: 'Determining product requirements',
        q: 'Are product requirements defined, including statutory and regulatory requirements and those the organization considers necessary, and can the organization meet its claims?',
        ev: 'Product specifications, legal requirements list, datasheets' },
      { id: '8.2.3-a', ref: '8.2.3', title: 'Review of requirements (contract review)',
        q: 'Before accepting orders, is a review done of customer requirements (including delivery and post-delivery), implied requirements, statutory requirements and feasibility, and are differing requirements resolved and verbal orders confirmed?',
        ev: 'Contract review / feasibility records, order acknowledgements' },
      { id: '8.2.3-b', ref: '8.2.3.2, 8.2.4', title: 'Records and changes to requirements',
        q: 'Are review results and new or changed requirements recorded, and when requirements change (e.g. drawing revision, quantity change) are documents updated and relevant people informed?',
        ev: 'Amendment records, ECN distribution' },
      { id: '8.3-a', ref: '8.3.1, 8.3.2', title: 'Design and development process and planning',
        q: 'If the organization designs products: is a D&D process established, with planned stages, reviews, verification and validation, responsibilities, resources, interfaces, customer involvement and required records? (Mark N/A with justification if build-to-print.)',
        ev: 'Design plan / APQP timing chart, project files' },
      { id: '8.3-b', ref: '8.3.3', title: 'Design inputs',
        q: 'Are design inputs complete and unambiguous: functional and performance requirements, previous designs, statutory requirements, standards, and potential consequences of failure (DFMEA), with conflicts resolved?',
        ev: 'Design input record, DFMEA' },
      { id: '8.3-c', ref: '8.3.4', title: 'Design controls',
        q: 'Are design reviews, verification (outputs vs inputs) and validation (product fit for intended use, e.g. prototype or field tests) carried out, with actions on problems and records kept?',
        ev: 'Design review minutes, test reports, validation reports' },
      { id: '8.3-d', ref: '8.3.5', title: 'Design outputs',
        q: 'Do design outputs (drawings, BOMs, specifications) meet inputs, suit production, include acceptance criteria and specify characteristics essential for safe and proper use?',
        ev: 'Released drawings, special characteristics list' },
      { id: '8.3-e', ref: '8.3.6', title: 'Design changes',
        q: 'Are design changes identified, reviewed, authorized and controlled to prevent adverse impact, with records kept?',
        ev: 'ECR/ECN records' },
      { id: '8.4-a', ref: '8.4.1', title: 'Control of external providers – general',
        q: 'Are controls defined for purchased materials and components, outsourced processes, and products supplied directly to customers by suppliers?',
        ev: 'Purchasing procedure, approved supplier list' },
      { id: '8.4-b', ref: '8.4.1', title: 'Supplier evaluation and re-evaluation',
        q: 'Are criteria applied for evaluating, selecting, monitoring and re-evaluating suppliers (e.g. quality, delivery, audit results), with records and follow-up actions?',
        ev: 'Supplier evaluation forms, supplier rating, supplier audits' },
      { id: '8.4-c', ref: '8.4.2', title: 'Type and extent of control',
        q: 'Is the level of control (incoming inspection, test certificates, source inspection) based on the impact on conformity and on the supplier\'s own controls, and are outsourced processes kept within QMS control?',
        ev: 'Incoming inspection plan, material test certificates, GRN records' },
      { id: '8.4-d', ref: '8.4.3', title: 'Information for external providers',
        q: 'Do purchase orders communicate adequate requirements: product/process specifications, approvals, release, required competence/qualifications, monitoring of supplier performance and any verification at the supplier\'s premises?',
        ev: 'Sample purchase orders, supplier quality agreements' },
      { id: '8.4-e', ref: '8.4.3 d)', title: 'Supplier interactions with customers and other parties',
        q: 'Where suppliers interact with your customers or other relevant parties (e.g. direct shipment, customer-nominated suppliers, joint audits), are these interactions defined and communicated to the supplier?',
        ev: 'Supplier agreements covering customer interfaces, drop-shipment instructions',
        change: { type: 'Modified', text: '2015 covered only the supplier\'s interactions with the organization. 2026 extends this to interactions with the organization\'s customers and other relevant interested parties, as applicable.' } },
      { id: '8.5.1-a', ref: '8.5.1', title: 'Controlled conditions for production',
        q: 'Is production carried out under controlled conditions: work instructions defining characteristics, activities and results; suitable measuring equipment; inspection at defined stages; suitable infrastructure; and competent, qualified operators?',
        ev: 'Work instructions at stations, inspection reports, set-up approval, operator qualifications' },
      { id: '8.5.1-b', ref: '8.5.1 f)', title: 'Validation of special processes',
        q: 'Are processes whose output cannot be fully verified afterwards (e.g. welding, heat treatment, painting, moulding, soldering) validated and periodically revalidated?',
        ev: 'Process validation / WPS-PQR records, revalidation schedule' },
      { id: '8.5.1-c', ref: '8.5.1 g), h)', title: 'Human error prevention, release and delivery',
        q: 'Are actions in place to prevent human error (poka-yoke, checklists, visual controls), and are release, delivery and post-delivery activities implemented?',
        ev: 'Poka-yoke list and verification, dispatch checklists' },
      { id: '8.5.2-a', ref: '8.5.2', title: 'Identification and traceability',
        q: 'Are materials and products identified throughout production, with inspection status clear (tags, labels, locations), and is traceability (batch, lot, heat number, serial) maintained with records where required?',
        ev: 'Tags/labels, traceability trace-back test, batch records' },
      { id: '8.5.3-a', ref: '8.5.3', title: 'Customer or supplier property',
        q: 'Is property belonging to customers or suppliers (dies, tooling, free-issue material, drawings, personal data) identified, verified, protected, and is loss or damage reported to the owner?',
        ev: 'Customer property register, tooling records, damage reports' },
      { id: '8.5.4-a', ref: '8.5.4', title: 'Preservation',
        q: 'Are outputs preserved during production and storage: handling, packaging, contamination control, rust prevention, FIFO, shelf-life control and transport?',
        ev: 'Packaging standards, storage conditions, FIFO / shelf-life records' },
      { id: '8.5.5-a', ref: '8.5.5', title: 'Post-delivery activities',
        q: 'Are post-delivery requirements (warranty, service, spares, recycling/disposal) met, considering legal requirements, risks, product lifetime, customer requirements and feedback?',
        ev: 'Warranty records, service reports' },
      { id: '8.5.6-a', ref: '8.5.6', title: 'Control of production changes',
        q: 'Are production changes (machine, method, material, operator, tooling) reviewed and controlled to ensure conformity, with records of review, authorization and actions?',
        ev: 'Process change records, first-off approvals after change' },
      { id: '8.6-a', ref: '8.6', title: 'Release of products',
        q: 'Is product released only after planned inspections are completed (or with authorized concession), and do release records show conformity to acceptance criteria and who authorized release?',
        ev: 'Final inspection reports, PDI, release signatures, concession approvals' },
      { id: '8.7-a', ref: '8.7.1', title: 'Control of nonconforming outputs',
        q: 'Are nonconforming products identified and segregated (red tag, quarantine area), handled by correction/rework, containment, informing the customer or concession, and re-verified after rework, including NCs found after delivery?',
        ev: 'Quarantine area, NC tags, rework records, customer notifications' },
      { id: '8.7-b', ref: '8.7.2', title: 'Nonconformity records',
        q: 'Are records kept of the nature of the nonconformity, actions taken, concessions obtained and who decided the action?',
        ev: 'NC register, MRB (material review board) records' }
    ]
  },
  {
    num: '9', title: 'Performance evaluation',
    items: [
      { id: '9.1.1-a', ref: '9.1.1', title: 'Monitoring and measurement – general',
        q: 'Has the organization determined what to monitor and measure, methods, when to measure and when to analyse, and is QMS performance and effectiveness evaluated with records retained?',
        ev: 'KPI dashboard, monitoring plan' },
      { id: '9.1.2-a', ref: '9.1.2', title: 'Customer satisfaction',
        q: 'Is customer satisfaction monitored with defined methods (surveys, customer scorecards, complaints, warranty claims, returns) and reviewed?',
        ev: 'Survey results, OEM scorecards, complaint analysis' },
      { id: '9.1.3-a', ref: '9.1.3', title: 'Analysis and evaluation',
        q: 'Is data analysed (e.g. SPC, Pareto, trend charts) to evaluate product conformity, customer satisfaction, QMS performance, effectiveness of planning, supplier performance and need for improvement?',
        ev: 'Monthly quality reports, SPC charts, supplier performance analysis' },
      { id: '9.1.3-b', ref: '9.1.3 e), f)', title: 'Effectiveness of risk and opportunity actions',
        q: 'Is the effectiveness of actions on risks and, separately, of actions on opportunities evaluated using data?',
        ev: 'Effectiveness review columns in risk and opportunity registers',
        change: { type: 'Modified', text: 'Effectiveness of actions on risks and on opportunities are now evaluated as two separate items (2015: one combined item).' } },
      { id: '9.2-a', ref: '9.2.1, 9.2.2', title: 'Internal audit programme',
        q: 'Is there an internal audit programme with frequency, methods, responsibilities and reporting, based on process importance, previous audit results and changes affecting the organization?',
        ev: 'Annual audit programme/schedule' },
      { id: '9.2-b', ref: '9.2.2 a)', title: 'Audit objectives, criteria and scope',
        q: 'Are the audit objectives, criteria and scope defined for each audit?',
        ev: 'Audit plans showing objectives, criteria and scope',
        change: { type: 'Modified', text: 'Audit objectives must now be defined for each audit, in addition to criteria and scope (2015: criteria and scope only).' } },
      { id: '9.2-c', ref: '9.2.2 b)–d)', title: 'Audit conduct and follow-up',
        q: 'Are auditors objective and impartial (not auditing their own work), results reported to relevant managers, and corrections and corrective actions taken without undue delay, with records kept?',
        ev: 'Auditor qualification, audit reports, NC closure status' },
      { id: '9.3-a', ref: '9.3.1', title: 'Management review',
        q: 'Does top management review the QMS at planned intervals for suitability, adequacy, effectiveness and alignment with strategic direction?',
        ev: 'MR schedule and minutes' },
      { id: '9.3-b', ref: '9.3.2', title: 'Management review inputs',
        q: 'Does the review cover previous actions, changes in internal/external issues, QMS performance trends (NCs, measurements, audits, customer satisfaction, objectives, process and product conformity, supplier performance), improvement opportunities and adequacy of resources?',
        ev: 'MR agenda and minutes' },
      { id: '9.3-c', ref: '9.3.2 c)', title: 'Changes in interested party needs',
        q: 'Does the management review include changes in the needs and expectations of relevant interested parties?',
        ev: 'MR minutes showing interested-party changes discussed',
        change: { type: 'New', text: 'New management review input c): changes in needs and expectations of interested parties relevant to the QMS.' } },
      { id: '9.3-d', ref: '9.3.2 g), h)', title: 'Review of risk and opportunity actions',
        q: 'Does the management review consider the effectiveness of actions on risks and, separately, of actions on opportunities?',
        ev: 'MR minutes, risk and opportunity register summaries',
        change: { type: 'Modified', text: 'Risks (g) and opportunities (h) are now separate management review inputs (2015: one combined input).' } },
      { id: '9.3-e', ref: '9.3.3', title: 'Management review results',
        q: 'Do the outputs include decisions on improvement opportunities, changes needed to the QMS and resource needs, with records retained?',
        ev: 'MR action list with owners and dates' }
    ]
  },
  {
    num: '10', title: 'Improvement',
    items: [
      { id: '10.1-a', ref: '10.1', title: 'Continual improvement',
        q: 'Are results of monitoring, analysis and management review used to determine improvement opportunities, and are actions taken to improve processes and products, address future needs and reduce undesired effects (e.g. Kaizen, lean, cost reduction projects)?',
        ev: 'Improvement project register, Kaizen sheets, before/after data' },
      { id: '10.2-a', ref: '10.2.1', title: 'Reaction and root cause analysis',
        q: 'When a nonconformity occurs (internal, supplier, customer complaint), does the organization contain and correct it, deal with consequences, find the root cause (5-Why, Ishikawa, 8D) and check whether similar NCs exist or could occur?',
        ev: 'CAPA/8D reports, complaint files' },
      { id: '10.2-b', ref: '10.2.1', title: 'Corrective action effectiveness',
        q: 'Are corrective actions implemented and their effectiveness reviewed, risks and opportunities updated, and QMS changes made where needed?',
        ev: 'CAPA closure with effectiveness verification, updated PFMEA / risk register' },
      { id: '10.2-c', ref: '10.2.2', title: 'Corrective action records',
        q: 'Are records kept of the nature of nonconformities, actions taken and results of corrective actions?',
        ev: 'CAPA register' }
    ]
  }
];
